name: Build, Test, and Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required for GitVersion to work correctly
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
    
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
    
    - name: Display GitVersion outputs
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersion }}"
    
    - name: Set Version Environment Variable
      run: echo "DOT_AGE_VERSION=${{ steps.gitversion.outputs.nuGetVersion }}" >> $GITHUB_ENV
    
    - name: Update nuspec version
      run: |
        sed -i "s/<version>.*<\/version>/<version>${{ env.DOT_AGE_VERSION }}<\/version>/" DotAge/DotAge.Core/DotAge.Core.nuspec
    
    - name: Restore dependencies
      run: dotnet restore DotAge/DotAge.sln
    
    - name: Build
      run: dotnet build DotAge/DotAge.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test DotAge/DotAge.sln --configuration Release --no-build --verbosity normal
    
    - name: Package
      run: |
        cd DotAge/DotAge.Core
        dotnet pack -c Release /p:NuspecFile=DotAge.Core.nuspec
    
    - name: Upload NuGet package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuget-package
        path: DotAge/DotAge.Core/bin/Release/DotAge.${{ env.DOT_AGE_VERSION }}.nupkg
    
    - name: Publish to NuGet
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        dotnet nuget push DotAge/DotAge.Core/bin/Release/DotAge.${{ env.DOT_AGE_VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json